<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?scdStore version="2"?><scannerInfo id="org.eclipse.cdt.make.core.discoveredScannerInfo">
<instance id="de.innot.avreclipse.configuration.app.debug.285952586;de.innot.avreclipse.configuration.app.debug.285952586.;de.innot.avreclipse.tool.compiler.winavr.app.debug.389129533;de.innot.avreclipse.compiler.winavr.input.407777362">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="/usr/bin/../lib/gcc/avr/4.1.2/include"/>
<includePath path="/usr/bin/../lib/gcc/avr/4.1.2/../../../../avr/include"/>
<definedSymbol symbol="__STDC__=1"/>
<definedSymbol symbol="__STDC_HOSTED__=1"/>
<definedSymbol symbol="__GNUC__=4"/>
<definedSymbol symbol="__GNUC_MINOR__=1"/>
<definedSymbol symbol="__GNUC_PATCHLEVEL__=2"/>
<definedSymbol symbol="__SIZE_TYPE__=unsigned int"/>
<definedSymbol symbol="__PTRDIFF_TYPE__=int"/>
<definedSymbol symbol="__WCHAR_TYPE__=int"/>
<definedSymbol symbol="__WINT_TYPE__=unsigned int"/>
<definedSymbol symbol="__INTMAX_TYPE__=long long int"/>
<definedSymbol symbol="__UINTMAX_TYPE__=long long unsigned int"/>
<definedSymbol symbol="__GXX_ABI_VERSION=1002"/>
<definedSymbol symbol="__USING_SJLJ_EXCEPTIONS__=1"/>
<definedSymbol symbol="__SCHAR_MAX__=127"/>
<definedSymbol symbol="__SHRT_MAX__=32767"/>
<definedSymbol symbol="__INT_MAX__=32767"/>
<definedSymbol symbol="__LONG_MAX__=2147483647L"/>
<definedSymbol symbol="__LONG_LONG_MAX__=9223372036854775807LL"/>
<definedSymbol symbol="__WCHAR_MAX__=32767"/>
<definedSymbol symbol="__CHAR_BIT__=8"/>
<definedSymbol symbol="__INTMAX_MAX__=9223372036854775807LL"/>
<definedSymbol symbol="__FLT_EVAL_METHOD__=0"/>
<definedSymbol symbol="__FLT_RADIX__=2"/>
<definedSymbol symbol="__FLT_MANT_DIG__=24"/>
<definedSymbol symbol="__FLT_DIG__=6"/>
<definedSymbol symbol="__FLT_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__FLT_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__FLT_MAX_EXP__=128"/>
<definedSymbol symbol="__FLT_MAX_10_EXP__=38"/>
<definedSymbol symbol="__FLT_MAX__=3.40282347e+38F"/>
<definedSymbol symbol="__FLT_MIN__=1.17549435e-38F"/>
<definedSymbol symbol="__FLT_EPSILON__=1.19209290e-7F"/>
<definedSymbol symbol="__FLT_DENORM_MIN__=1.40129846e-45F"/>
<definedSymbol symbol="__FLT_HAS_INFINITY__=1"/>
<definedSymbol symbol="__FLT_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__DBL_MANT_DIG__=24"/>
<definedSymbol symbol="__DBL_DIG__=6"/>
<definedSymbol symbol="__DBL_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__DBL_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__DBL_MAX_EXP__=128"/>
<definedSymbol symbol="__DBL_MAX_10_EXP__=38"/>
<definedSymbol symbol="__DBL_MAX__=3.40282347e+38"/>
<definedSymbol symbol="__DBL_MIN__=1.17549435e-38"/>
<definedSymbol symbol="__DBL_EPSILON__=1.19209290e-7"/>
<definedSymbol symbol="__DBL_DENORM_MIN__=1.40129846e-45"/>
<definedSymbol symbol="__DBL_HAS_INFINITY__=1"/>
<definedSymbol symbol="__DBL_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__LDBL_MANT_DIG__=24"/>
<definedSymbol symbol="__LDBL_DIG__=6"/>
<definedSymbol symbol="__LDBL_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__LDBL_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__LDBL_MAX_EXP__=128"/>
<definedSymbol symbol="__LDBL_MAX_10_EXP__=38"/>
<definedSymbol symbol="__DECIMAL_DIG__=9"/>
<definedSymbol symbol="__LDBL_MAX__=3.40282347e+38L"/>
<definedSymbol symbol="__LDBL_MIN__=1.17549435e-38L"/>
<definedSymbol symbol="__LDBL_EPSILON__=1.19209290e-7L"/>
<definedSymbol symbol="__LDBL_DENORM_MIN__=1.40129846e-45L"/>
<definedSymbol symbol="__LDBL_HAS_INFINITY__=1"/>
<definedSymbol symbol="__LDBL_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__REGISTER_PREFIX__="/>
<definedSymbol symbol="__USER_LABEL_PREFIX__="/>
<definedSymbol symbol="__VERSION__=&quot;4.1.2&quot;"/>
<definedSymbol symbol="__NO_INLINE__=1"/>
<definedSymbol symbol="__FINITE_MATH_ONLY__=0"/>
<definedSymbol symbol="__AVR=1"/>
<definedSymbol symbol="__AVR__=1"/>
<definedSymbol symbol="AVR=1"/>
<definedSymbol symbol="__AVR_ARCH__=5"/>
<definedSymbol symbol="__AVR_ATmega644__=1"/>
<definedSymbol symbol="__AVR_2_BYTE_PC__=1"/>
<definedSymbol symbol="__AVR_ENHANCED__=1"/>
<definedSymbol symbol="__AVR_MEGA__=1"/>
<definedSymbol symbol="F_CPU=1000000UL"/>
</collector>
</instance>
<instance id="de.innot.avreclipse.configuration.app.release.330589143;de.innot.avreclipse.configuration.app.release.330589143.;de.innot.avreclipse.tool.compiler.winavr.app.release.1758077730;de.innot.avreclipse.compiler.winavr.input.288289248">
<collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
<includePath path="/usr/bin/../lib/gcc/avr/4.1.2/include"/>
<includePath path="/usr/bin/../lib/gcc/avr/4.1.2/../../../../avr/include"/>
<definedSymbol symbol="__STDC__=1"/>
<definedSymbol symbol="__STDC_HOSTED__=1"/>
<definedSymbol symbol="__GNUC__=4"/>
<definedSymbol symbol="__GNUC_MINOR__=1"/>
<definedSymbol symbol="__GNUC_PATCHLEVEL__=2"/>
<definedSymbol symbol="__SIZE_TYPE__=unsigned int"/>
<definedSymbol symbol="__PTRDIFF_TYPE__=int"/>
<definedSymbol symbol="__WCHAR_TYPE__=int"/>
<definedSymbol symbol="__WINT_TYPE__=unsigned int"/>
<definedSymbol symbol="__INTMAX_TYPE__=long long int"/>
<definedSymbol symbol="__UINTMAX_TYPE__=long long unsigned int"/>
<definedSymbol symbol="__GXX_ABI_VERSION=1002"/>
<definedSymbol symbol="__USING_SJLJ_EXCEPTIONS__=1"/>
<definedSymbol symbol="__SCHAR_MAX__=127"/>
<definedSymbol symbol="__SHRT_MAX__=32767"/>
<definedSymbol symbol="__INT_MAX__=32767"/>
<definedSymbol symbol="__LONG_MAX__=2147483647L"/>
<definedSymbol symbol="__LONG_LONG_MAX__=9223372036854775807LL"/>
<definedSymbol symbol="__WCHAR_MAX__=32767"/>
<definedSymbol symbol="__CHAR_BIT__=8"/>
<definedSymbol symbol="__INTMAX_MAX__=9223372036854775807LL"/>
<definedSymbol symbol="__FLT_EVAL_METHOD__=0"/>
<definedSymbol symbol="__FLT_RADIX__=2"/>
<definedSymbol symbol="__FLT_MANT_DIG__=24"/>
<definedSymbol symbol="__FLT_DIG__=6"/>
<definedSymbol symbol="__FLT_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__FLT_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__FLT_MAX_EXP__=128"/>
<definedSymbol symbol="__FLT_MAX_10_EXP__=38"/>
<definedSymbol symbol="__FLT_MAX__=3.40282347e+38F"/>
<definedSymbol symbol="__FLT_MIN__=1.17549435e-38F"/>
<definedSymbol symbol="__FLT_EPSILON__=1.19209290e-7F"/>
<definedSymbol symbol="__FLT_DENORM_MIN__=1.40129846e-45F"/>
<definedSymbol symbol="__FLT_HAS_INFINITY__=1"/>
<definedSymbol symbol="__FLT_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__DBL_MANT_DIG__=24"/>
<definedSymbol symbol="__DBL_DIG__=6"/>
<definedSymbol symbol="__DBL_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__DBL_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__DBL_MAX_EXP__=128"/>
<definedSymbol symbol="__DBL_MAX_10_EXP__=38"/>
<definedSymbol symbol="__DBL_MAX__=3.40282347e+38"/>
<definedSymbol symbol="__DBL_MIN__=1.17549435e-38"/>
<definedSymbol symbol="__DBL_EPSILON__=1.19209290e-7"/>
<definedSymbol symbol="__DBL_DENORM_MIN__=1.40129846e-45"/>
<definedSymbol symbol="__DBL_HAS_INFINITY__=1"/>
<definedSymbol symbol="__DBL_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__LDBL_MANT_DIG__=24"/>
<definedSymbol symbol="__LDBL_DIG__=6"/>
<definedSymbol symbol="__LDBL_MIN_EXP__=(-125)"/>
<definedSymbol symbol="__LDBL_MIN_10_EXP__=(-37)"/>
<definedSymbol symbol="__LDBL_MAX_EXP__=128"/>
<definedSymbol symbol="__LDBL_MAX_10_EXP__=38"/>
<definedSymbol symbol="__DECIMAL_DIG__=9"/>
<definedSymbol symbol="__LDBL_MAX__=3.40282347e+38L"/>
<definedSymbol symbol="__LDBL_MIN__=1.17549435e-38L"/>
<definedSymbol symbol="__LDBL_EPSILON__=1.19209290e-7L"/>
<definedSymbol symbol="__LDBL_DENORM_MIN__=1.40129846e-45L"/>
<definedSymbol symbol="__LDBL_HAS_INFINITY__=1"/>
<definedSymbol symbol="__LDBL_HAS_QUIET_NAN__=1"/>
<definedSymbol symbol="__REGISTER_PREFIX__="/>
<definedSymbol symbol="__USER_LABEL_PREFIX__="/>
<definedSymbol symbol="__VERSION__=&quot;4.1.2&quot;"/>
<definedSymbol symbol="__NO_INLINE__=1"/>
<definedSymbol symbol="__FINITE_MATH_ONLY__=0"/>
<definedSymbol symbol="__AVR=1"/>
<definedSymbol symbol="__AVR__=1"/>
<definedSymbol symbol="AVR=1"/>
<definedSymbol symbol="__AVR_ARCH__=5"/>
<definedSymbol symbol="__AVR_ATmega644__=1"/>
<definedSymbol symbol="__AVR_2_BYTE_PC__=1"/>
<definedSymbol symbol="__AVR_ENHANCED__=1"/>
<definedSymbol symbol="__AVR_MEGA__=1"/>
<definedSymbol symbol="F_CPU=1000000UL"/>
</collector>
</instance>
</scannerInfo>
